// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: otpauth.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationPayload struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	OtpParameters []*MigrationPayload_OTPParameters `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters,proto3" json:"otp_parameters,omitempty"`
	Version       int32                             `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BatchSize     int32                             `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchIndex    int32                             `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	BatchId       int32                             `protobuf:"varint,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload) Reset() {
	*x = MigrationPayload{}
	mi := &file_otpauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload) ProtoMessage() {}

func (x *MigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_otpauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload.ProtoReflect.Descriptor instead.
func (*MigrationPayload) Descriptor() ([]byte, []int) {
	return file_otpauth_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationPayload) GetOtpParameters() []*MigrationPayload_OTPParameters {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

func (x *MigrationPayload) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MigrationPayload) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *MigrationPayload) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *MigrationPayload) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type MigrationPayload_OTPParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algorithm     int32                  `protobuf:"varint,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Digits        int32                  `protobuf:"varint,5,opt,name=digits,proto3" json:"digits,omitempty"`
	Counter       int64                  `protobuf:"varint,6,opt,name=counter,proto3" json:"counter,omitempty"`
	Type          int32                  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload_OTPParameters) Reset() {
	*x = MigrationPayload_OTPParameters{}
	mi := &file_otpauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload_OTPParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload_OTPParameters) ProtoMessage() {}

func (x *MigrationPayload_OTPParameters) ProtoReflect() protoreflect.Message {
	mi := &file_otpauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload_OTPParameters.ProtoReflect.Descriptor instead.
func (*MigrationPayload_OTPParameters) Descriptor() ([]byte, []int) {
	return file_otpauth_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MigrationPayload_OTPParameters) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *MigrationPayload_OTPParameters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationPayload_OTPParameters) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *MigrationPayload_OTPParameters) GetAlgorithm() int32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *MigrationPayload_OTPParameters) GetDigits() int32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *MigrationPayload_OTPParameters) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *MigrationPayload_OTPParameters) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_otpauth_proto protoreflect.FileDescriptor

const file_otpauth_proto_rawDesc = "" +
	"\n" +
	"\rotpauth.proto\"\x89\x03\n" +
	"\x10MigrationPayload\x12F\n" +
	"\x0eotp_parameters\x18\x01 \x03(\v2\x1f.MigrationPayload.OTPParametersR\rotpParameters\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vbatch_index\x18\x04 \x01(\x05R\n" +
	"batchIndex\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\x05R\abatchId\x1a\xb7\x01\n" +
	"\rOTPParameters\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\x05R\talgorithm\x12\x16\n" +
	"\x06digits\x18\x05 \x01(\x05R\x06digits\x12\x18\n" +
	"\acounter\x18\x06 \x01(\x03R\acounter\x12\x12\n" +
	"\x04type\x18\a \x01(\x05R\x04typeB\bZ\x06.;mainb\x06proto3"

var (
	file_otpauth_proto_rawDescOnce sync.Once
	file_otpauth_proto_rawDescData []byte
)

func file_otpauth_proto_rawDescGZIP() []byte {
	file_otpauth_proto_rawDescOnce.Do(func() {
		file_otpauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otpauth_proto_rawDesc), len(file_otpauth_proto_rawDesc)))
	})
	return file_otpauth_proto_rawDescData
}

var file_otpauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_otpauth_proto_goTypes = []any{
	(*MigrationPayload)(nil),               // 0: MigrationPayload
	(*MigrationPayload_OTPParameters)(nil), // 1: MigrationPayload.OTPParameters
}
var file_otpauth_proto_depIdxs = []int32{
	1, // 0: MigrationPayload.otp_parameters:type_name -> MigrationPayload.OTPParameters
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_otpauth_proto_init() }
func file_otpauth_proto_init() {
	if File_otpauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otpauth_proto_rawDesc), len(file_otpauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_otpauth_proto_goTypes,
		DependencyIndexes: file_otpauth_proto_depIdxs,
		MessageInfos:      file_otpauth_proto_msgTypes,
	}.Build()
	File_otpauth_proto = out.File
	file_otpauth_proto_goTypes = nil
	file_otpauth_proto_depIdxs = nil
}
